/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELBishopWhite_H__
# define __3D_MODELBishopWhite_H__

static POINT    PointBishopWhite[] =
{
	{-327680, -1191563, -327680},
	{-327680, -1191563, 327680},
	{-327680, 0, -327680},
	{-327680, 0, 327680},
	{327680, -1191563, -327680},
	{327680, -1191563, 327680},
	{327680, 0, -327680},
	{327680, 0, 327680},
};

static POLYGON    PolygonBishopWhite[] =
{
	{{-65536, 0, 0}, {1, 3, 2, 0}},
	{{0, 0, 0}, {3, 7, 6, 2}},
	{{0, 0, 65536}, {7, 5, 4, 6}},
	{{0, 65536, 0}, {5, 1, 0, 4}},
	{{65536, 0, 65536}, {0, 2, 6, 4}},
	{{0, 65536, 0}, {5, 7, 3, 1}},
};

static ATTR    AttributeBishopWhite[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshBishopWhite =
{
	.data =
	{
		PointBishopWhite,
		8,
		PolygonBishopWhite,
		6,
		AttributeBishopWhite
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_bishop_white_mesh(void)
{
	jo_3d_rotate_matrix_y(45);
	jo_3d_set_scale(5, 10, 5);
	jo_3d_mesh_draw(&MeshBishopWhite);
}

#endif /* !__3D_MODELBishopWhite_H__ */
