/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELPawnWhite_H__
# define __3D_MODELPawnWhite_H__

static POINT    PointPawnWhite[] =
{
	{-327680, -1191563, -327680},
	{-327680, -1191563, 327680},
	{-327680, 0, -327680},
	{-327680, 0, 327680},
	{327680, -1191563, -327680},
	{327680, -1191563, 327680},
	{327680, 0, -327680},
	{327680, 0, 327680},
};

static POLYGON    PolygonPawnWhite[] =
{
	{{-65536, 0, 0}, {1, 3, 2, 0}},
	{{0, 0, 0}, {3, 7, 6, 2}},
	{{0, 0, 65536}, {7, 5, 4, 6}},
	{{0, 65536, 0}, {5, 1, 0, 4}},
	{{65536, 0, 65536}, {0, 2, 6, 4}},
	{{0, 65536, 0}, {5, 7, 3, 1}},
};

static ATTR    AttributePawnWhite[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshPawnWhite =
{
	.data =
	{
		PointPawnWhite,
		8,
		PolygonPawnWhite,
		6,
		AttributePawnWhite
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_pawn_white_mesh(void)
{
	jo_3d_set_scale(5, 5, 5);
	jo_3d_mesh_draw(&MeshPawnWhite);
}

#endif /* !__3D_MODELPawnWhite_H__ */
